name: 部署到阿里云
on:
  push:
    branches: [main]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 检查并打包源目录
        run: |
          SOURCE_DIR="${{github.workspace}}"  # 替换为实际目录
          if [ ! -d "$SOURCE_DIR" ] || [ -z "$(ls -A $SOURCE_DIR)" ]; then
            echo "源目录不存在或为空: $SOURCE_DIR"
            exit 1
          fi
          tar -czf /tmp/archive.tar.gz -C "$SOURCE_DIR" .

      - name: 确保 dist 目录存在
        run: |
          DIST_DIR="${{github.workspace}}/dist"
          mkdir -p "$DIST_DIR"
          if [ ! -d "$DIST_DIR" ]; then
            echo "dist 目录创建失败: $DIST_DIR"
            exit 1
          fi

      - name: 部署到阿里云
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/lacrymira-site/"

      - name: 设置权限并重启 Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chown -R nginx:nginx /var/www/lacrymira-site
            sudo systemctl restart nginx