name: Deploy to Aliyun
on:
  push:
    branches: [main]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug directory
        run: |
          echo "Workspace:${{github.workspace}}"
          ls -la ${{github.workspace}}

      # 尝试搜寻对应根目录
      - name: Debug directory structure
        run: |
          echo "Listing all files:"
          find ${{github.workspace}}

      # 可选：构建步骤（如使用 Hugo、Vite 等）
      - name: Build Static Site
        run: |
          cd ${{github.workspace}}
          npm install
          npm run build
          # 构建后的文件默认在 dist/ 目录

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}    # 服务器 IP（需添加到 GitHub Secrets）
          username: ${{ secrets.SERVER_USER }}  # 服务器用户名（如 root 或 ubuntu）
          key: ${{ secrets.SERVER_SSH_KEY }}    # 已配置的私钥
          script: |
            cd /var/www/lacrymira-site
            git pull origin main  # 若直接拉取仓库
            # 若需覆盖文件（如构建后的 dist/ 内容）：
            rm -rf /var/www/lacrymira-site/*
            cp -r $HOME/actions-runner/_work/your-repo/your-repo/dist/* /var/www/lacrymira-site/
            # 设置权限（根据 Web 服务器用户调整）
            sudo chown -R www-data:www-data /var/www/lacrymira-site
            sudo systemctl restart nginx